package de.hdm.hdmUrlaub.db.dbmodel;

// Generated 03.01.2015 17:25:14 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mitarbeiter generated by hbm2java
 */
@Entity
@Table(name = "mitarbeiter", catalog = "mydb")
public class Mitarbeiter extends HibernateObject {

	private static final long serialVersionUID = -5465288035458506806L;
	private Integer id;
	private String vorname;
	private String nachname;
	private String email;
	private String passwort;
	private Set<Urlaubsantrag> urlaubsantrags = new HashSet<Urlaubsantrag>(0);

	public Mitarbeiter() {
	}

	public Mitarbeiter(String vorname, String nachname, String email,
			String passwort) {
		this.vorname = vorname;
		this.nachname = nachname;
		this.email = email;
		this.passwort = passwort;

	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "vorname", length = 45)
	public String getVorname() {
		return this.vorname;
	}

	public void setVorname(String vorname) {
		this.vorname = vorname;
	}

	@Column(name = "nachname", length = 45)
	public String getNachname() {
		return this.nachname;
	}

	public void setNachname(String nachname) {
		this.nachname = nachname;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "passwort", length = 45)
	public String getPasswort() {
		return this.passwort;
	}

	public void setPasswort(String passwort) {
		this.passwort = passwort;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mitarbeiter")
	public Set<Urlaubsantrag> getUrlaubsantrags() {
		return this.urlaubsantrags;
	}

	public void setUrlaubsantrags(Set<Urlaubsantrag> urlaubsantrags) {
		this.urlaubsantrags = urlaubsantrags;
	}

}
