package de.hdm.hdmUrlaub.db.dbmodel;

// Generated 03.01.2015 17:25:14 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Urlaubsantrag generated by hbm2java
 */
@Entity
@Table(name = "urlaubsantrag", catalog = "mydb")
public class Urlaubsantrag extends HibernateObject {

	private static final long serialVersionUID = -6371359530884209703L;
	private Integer id;
	private Mitarbeiter mitarbeiter;
	private Fachvorgesetzter fachvorgesetzter;
	private Character status;
	private Integer anzahltage;
	private String vertretung;
	private String activationKey;
	private String begruendung;
	private Set<Zeitraum> zeitraums = new HashSet<Zeitraum>(0);

	public Urlaubsantrag() {
	}

	public Urlaubsantrag(Mitarbeiter mitarbeiter,
			Fachvorgesetzter fachvorgesetzter) {
		this.mitarbeiter = mitarbeiter;
		this.fachvorgesetzter = fachvorgesetzter;
	}

	public Urlaubsantrag(Integer id, Mitarbeiter mitarbeiter,
			Fachvorgesetzter fachvorgesetzter, Character status,
			Integer anzahltage, String vertretung, Set<Zeitraum> zeitraums) {
		this.id = id;
		this.mitarbeiter = mitarbeiter;
		this.fachvorgesetzter = fachvorgesetzter;
		this.status = status;
		this.anzahltage = anzahltage;
		this.vertretung = vertretung;
		this.zeitraums = zeitraums;
	}

	public Urlaubsantrag(Integer id, Mitarbeiter mitarbeiter,
			Fachvorgesetzter fachvorgesetzter, Character status,
			Integer anzahltage, String vertretung, String activationKey,
			String begruendung, Set<Zeitraum> zeitraums) {
		this.id = id;
		this.mitarbeiter = mitarbeiter;
		this.fachvorgesetzter = fachvorgesetzter;
		this.status = status;
		this.anzahltage = anzahltage;
		this.vertretung = vertretung;
		this.activationKey = activationKey;
		this.begruendung = begruendung;
		this.zeitraums = zeitraums;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mitarbeiter_id", nullable = false)
	public Mitarbeiter getMitarbeiter() {
		return this.mitarbeiter;
	}

	public void setMitarbeiter(Mitarbeiter mitarbeiter) {
		this.mitarbeiter = mitarbeiter;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fachvorgesetzter_id", nullable = false)
	public Fachvorgesetzter getFachvorgesetzter() {
		return this.fachvorgesetzter;
	}

	public void setFachvorgesetzter(Fachvorgesetzter fachvorgesetzter) {
		this.fachvorgesetzter = fachvorgesetzter;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "anzahltage")
	public Integer getAnzahltage() {
		return this.anzahltage;
	}

	public void setAnzahltage(Integer anzahltage) {
		this.anzahltage = anzahltage;
	}

	@Column(name = "vertretung", length = 45)
	public String getVertretung() {
		return this.vertretung;
	}

	public void setVertretung(String vertretung) {
		this.vertretung = vertretung;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "urlaubsantrag", cascade = CascadeType.ALL)
	public Set<Zeitraum> getZeitraums() {
		return this.zeitraums;
	}

	public void setZeitraums(Set<Zeitraum> zeitraums) {
		this.zeitraums = zeitraums;
	}

	@Column(name = "activationKey", length = 200)
	public String getActivationKey() {
		return activationKey;
	}

	public void setActivationKey(String activationKey) {
		this.activationKey = activationKey;
	}

	@Column(name = "begruendung")
	public String getBegruendung() {
		return begruendung;
	}

	public void setBegruendung(String begruendung) {
		this.begruendung = begruendung;
	}

}
