package de.hdm.hdmUrlaub.db.dbmodel;

// Generated 03.01.2015 17:25:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Zeitraum generated by hbm2java
 */
@Entity
@Table(name = "zeitraum", catalog = "mydb")
public class Zeitraum extends HibernateObject {

	private static final long serialVersionUID = -5997665572839340806L;
	private Integer id;
	private Urlaubsantrag urlaubsantrag;
	private Date beginn;
	private Date ende;

	public Zeitraum() {
	}

	public Zeitraum(Urlaubsantrag urlaubsantrag) {
		this.urlaubsantrag = urlaubsantrag;
	}

	public Zeitraum(Date beginn, Date ende) {
		super();
		this.beginn = beginn;
		this.ende = ende;
	}

	public Zeitraum(Urlaubsantrag urlaubsantrag, Date beginn, Date ende) {
		this.urlaubsantrag = urlaubsantrag;
		this.beginn = beginn;
		this.ende = ende;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "urlaubsantrag_id", nullable = false)
	public Urlaubsantrag getUrlaubsantrag() {
		return this.urlaubsantrag;
	}

	public void setUrlaubsantrag(Urlaubsantrag urlaubsantrag) {
		this.urlaubsantrag = urlaubsantrag;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "beginn", length = 10)
	public Date getBeginn() {
		return this.beginn;
	}

	public void setBeginn(Date beginn) {
		this.beginn = beginn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ende", length = 10)
	public Date getEnde() {
		return this.ende;
	}

	public void setEnde(Date ende) {
		this.ende = ende;
	}

}
